In [39]:
# import relevant modules and files

import numpy as np
import pandas as pd
import mkl
mkl.set_num_threads(1) # set the number of python threads to be 1 to stop the python parallelisation

df_annotations = {}

for i in range(1, 23):
    df_annotations[i] = pd.read_csv(f"{i}permutationready.tsv", sep="\t")


In [2]:
annotations = ['3_prime_UTR_variant','5_prime_UTR_variant','NMD_transcript_variant','coding_sequence_variant','downstream_gene_variant','incomplete_terminal_codon_variant','intergenic_variant','intron_variant','mature_miRNA_variant','missense_variant','non_coding_transcript_exon_variant','non_coding_transcript_variant','splice_acceptor_variant','splice_donor_variant','splice_region_variant','start_lost','stop_gained','stop_lost','stop_retained_variant','synonymous_variant','upstream_gene_variant']


In [3]:
# do for all chromosomes
df_noheader = {}
np_df = {}
location_vec = {}
annotation_matrix = {}
a_matrix = {}

for i in range(1,23):
    df_noheader[i] = df_annotations[i].copy()
    np_df[i] = df_noheader[i].to_numpy()
    location_vec[i] = np_df[i][::,1]
    annotation_matrix[i] = np_df[i][::,2:]
    a_matrix[i] = annotation_matrix[i].transpose()
    
    

In [7]:
location_vec[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [19]:
np.shape(location_vec[1])

(948317,)

In [4]:
import random
import time
from multiprocessing import Process, Manager
import multiprocessing as mp

In [8]:
# make a function that counts:
tic = time.time()
def permutations(j):
    count_matrix = {}
    count_matrix[i] = np.zeros((21,1000)) # alternatively, can change numpy to be column-based from row-based when initialising the matrix, np.zeros((22,21), order='F')

    for i in range(1,23):
        r = random.randint(0, len(location_vec[i]))
        new_loc = np.roll(location_vec[i], r)
        c_vec = np.matmul(a_matrix[i], new_loc)
        count_matrix[i][:,j] = c_vec # each perm stored as row, remember to transpose
    return(count_matrix)
          
process_refs = []
# manager = Manager()
#count_matrix = manager.dict()

from multiprocessing import Pool
with Pool(processes=8) as pool:
    results = pool.map(permutations, [j for j in range(1000)])
# remember: 'result' is a list corresponding to the js   
toc = time.time()
time_taken = toc - tic
print(results)
print("time = {}".format(time_taken))
# for j in range(1, 10):
    # count_matrix[j] = manager.list()
   #  p = Process(target=permutations, args=(j, )) 
    
   # p.start()
   # process_refs.append(p)

#for p in process_refs:
    #p.join()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



TypeError: can only concatenate str (not "float") to str

In [8]:
# make a function that counts:
tic = time.time()
def permutations(j):
    count_matrix = {}
    #count_matrix[i] = np.zeros((21,1000)) # alternatively, can change numpy to be column-based from row-based when initialising the matrix, np.zeros((22,21), order='F')
    count_matrix = np.zeros((22, 21, 1000))
    for i in range(0,22):
        r = random.randint(0, len(location_vec[i+1]))
        new_loc = np.roll(location_vec[i+1], r)
        c_vec = np.matmul(a_matrix[i+1], new_loc)
        count_matrix[i][:,j] = c_vec # each perm stored as row, remember to transpose
    return(count_matrix)
          
process_refs = []
# manager = Manager()
#count_matrix = manager.dict()

from multiprocessing import Pool
with Pool(processes=8) as pool:
    results = pool.map(permutations, [j for j in range(1000)])
# remember: 'result' is a list corresponding to the js   
toc = time.time()
time_taken = toc - tic
print(results)
print("time = {}".format(time_taken))
# for j in range(1, 10):
    # count_matrix[j] = manager.list()
   #  p = Process(target=permutations, args=(j, )) 
    
   # p.start()
   # process_refs.append(p)

#for p in process_refs:
    #p.join()

[array([[[ 3.,  0.,  0., ...,  0.,  0.,  0.],
        [ 2.,  0.,  0., ...,  0.,  0.,  0.],
        [32.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [43.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [15.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [20.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 7.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [36.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [17.,  0.,  0., ...,  0.,  0.,  0.]],

       ...,

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 2.,  0.,  0., ...,  0.,  0.,  0

In [41]:
# make a function that counts:
tic = time.time()
def permutations(i): # where i is the number of chromosomes
    count_matrix = {}
    #count_matrix[i] = np.zeros((21,1000)) # alternatively, can change numpy to be column-based from row-based when initialising the matrix, np.zeros((22,21), order='F')
    count_matrix[i] = np.zeros((21, 1000))
    for j in range(0,1000):
        r = random.randint(0, len(location_vec[i+1]))
        new_loc = np.roll(location_vec[i+1], r)
        c_vec = np.matmul(a_matrix[i+1], new_loc)
        count_matrix[i][:,j] = c_vec # each perm stored as row, remember to transpose
    return(count_matrix)
          
process_refs = []
# manager = Manager()
#count_matrix = manager.dict()

from multiprocessing import Pool
with Pool(processes=8) as pool:
    results = pool.map(permutations, [i for i in range(22)])
# remember: 'result' is a list corresponding to the js   
toc = time.time()
time_taken = toc - tic
print(results)
print("time = {}".format(time_taken))
# for j in range(1, 10):
    # count_matrix[j] = manager.list()
   #  p = Process(target=permutations, args=(j, )) 
    
   # p.start()
   # process_refs.append(p)

#for p in process_refs:
    #p.join()
    
# remember to compare with numpy

[{0: array([[ 1.,  7.,  8., ...,  4.,  4.,  3.],
       [ 1.,  0.,  1., ...,  1.,  1.,  0.],
       [ 7., 21., 29., ..., 14., 12., 10.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 6.,  4.,  4., ...,  1.,  0.,  3.],
       [51., 48., 39., ..., 47., 41., 44.]])}, {1: array([[ 0.,  3.,  2., ...,  2.,  1.,  5.],
       [ 0.,  0.,  2., ...,  0.,  0.,  1.],
       [26., 25., 31., ..., 14., 34., 54.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  1.,  0., ...,  1.,  3.,  0.],
       [17., 20., 21., ..., 32., 33., 28.]])}, {2: array([[ 2.,  6.,  7., ...,  3.,  3.,  1.],
       [ 2.,  1.,  2., ...,  1.,  0.,  2.],
       [19., 40., 33., ..., 35., 21., 26.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  3.,  7., ...,  2.,  1.,  1.],
       [17., 30., 31., ..., 40., 22., 22.]])}, {3: array([[ 0.,  1.,  1., ...,  5.,  0.,  3.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [21., 13., 22., ..., 17., 14., 32.],
       ...,
  

In [36]:
results[1][1]

(21, 1000)

In [42]:
print(time_taken)

33.213109254837036


In [18]:
list(count_matrix[1])

[]

In [40]:
count_matrix = {}

tic = time.time()


for i in range(1,23):

    count_matrix[i] = np.zeros((21,1000))
    
    for j in range(0,1000):
        r = random.randint(0, len(location_vec[i]))
        new_loc = np.roll(location_vec[i], r)
        c_vec = np.matmul(a_matrix[i], new_loc)
        count_matrix[i][:,j] = c_vec
    
toc = time.time()
print("Time taken: {}".format(toc-tic))

# took 1902.6005499362946 seconds

Time taken: 184.6904628276825


In [8]:
# save as dataframe

for i in range(1,23):
    pd.DataFrame(count_matrix[i]).to_csv(f"{i}_permutation_data.tsv", sep="\t", index=False)

In [9]:
# calculate original number of sign SNPs in each annotation

original_number = {}

for i in range(1,23):
    original_number[i] = np.matmul(a_matrix[i],location_vec[i])


In [15]:
# graph the data
import matplotlib.pyplot as plt
# for chromosome i, annotation k:
# distribution_matrix[i][k,::] is the values of how many sign SNPs are in that annotation
i = 1
for k in range(0,21):
    plt.figure()
    plt.hist(count_matrix[i][k,::], bins=100)
    plt.gca().set(title='Transcript count Histogram', ylabel='Frequency', xlabel='Number of significant SNPs')
    plt.rcParams['figure.figsize'] = [20, 10]
    plt.axvline(x=original_number[i][k], color='r', label= 'observed number' )
    plt.title('Chromosome ' + str(i) + ' with annotation "' + annotations[k] +'"')
    plt.savefig("figure_"+str(k)+"_chrom_"+str(i))
    plt.close()

In [ ]:
# count_matrix[n] for chromosome n (starts at 1, ends at 22)
# count_matrix[n][k,::] for annotation k (starts at 0, ends at 20)
# count_matrix[n][::,j] for permutation j (starts at 0, ends at 9999)

In [10]:
from collections import Counter

freq_matrix = {} # for all chromosomes

for i in range(1,23):
    
    freq_matrix[i] = {}

    for j in range(0,21):
            freq_matrix[i][j] = Counter(count_matrix[i][j,::]) # count all permutations for one annotation

In [2]:
# freq_matrix[n] is the frequency counter for chromosome n (starts at 1, ends at 22)
# freq_matrix[n][k] is the frequency counter for annotation k, chromosome n (starts at 0, ends at 20)
# freq_matrix[n][k][j] is the number of counts in j 

#freq_matrix[4]

In [11]:
# calculating enrichment
enrichment_matrix = np.zeros((22,21))

for i in range(0,22):
# each row is the count nr in the corresponding chromosome n-1 (so row 0 corresponds to chrom 1)
    for k in range(0,21): # k is the annotation nr
        for l in freq_matrix[i+1][k]: # l is number of sign SNP in annotation
            if l >= original_number[i+1][k]: # and original_number[i+1][k] != 0: 
                enrichment_matrix[i][k] = enrichment_matrix[i][k] + freq_matrix[i+1][k][l] # freq_matrix[i+1][k][l] 
                                                                              # is nr of counts of l sign SNP 
                                                                              # in annotation
                        
p_vals_e = enrichment_matrix/10000 #pvals for enrichment

# find the significant ones

idx = np.where((0 < p_vals_e) & (p_vals_e < 0.05)) # location of significant values

print(idx)
print(p_vals_e[(0 < p_vals_e) & (p_vals_e < 0.05)])

(array([ 0,  0,  0,  0,  1,  1,  1,  1,  2,  3,  3,  3,  6,  6,  6,  8, 10,
       10, 10, 11, 12, 13, 14, 15]), array([ 0,  1,  4, 20,  4,  7, 11, 13, 20,  0,  9, 16,  4, 10, 20,  9,  1,
        4, 20, 20,  1,  4, 16, 13]))
[0.0391 0.0049 0.0277 0.0116 0.0012 0.024  0.0129 0.0342 0.0033 0.0451
 0.0077 0.0153 0.0037 0.005  0.0013 0.0012 0.0087 0.0006 0.0071 0.0329
 0.0433 0.008  0.0266 0.0471]


In [13]:
# Calculating depletion

depletion_matrix = np.zeros((22,21))

for i in range(0,22):
# each row is the count nr in the corresponding chromosome n-1 (so row 0 corresponds to chrom 1)
    for k in range(0,21): # k is the annotation nr
        for l in freq_matrix[i+1][k]: # l is number of sign SNP in annotation
            if l <= original_number[i+1][k]: # and original_number[i+1][k] != 0: 
                depletion_matrix[i][k] = depletion_matrix[i][k] + freq_matrix[i+1][k][l] # freq_matrix[i+1][k][l] 
                                                                              # is nr of counts of l sign SNP 
                                                                              # in annotation

In [16]:
p_vals_d = depletion_matrix/10000 #pvals for enrichment

# find the significant ones

idx2 = np.where((0 < p_vals_d) & (p_vals_d < 0.05)) # location of significant values

print(idx2)
print(p_vals_d[(0 < p_vals_d) & (p_vals_d < 0.05)])

(array([ 0,  1,  2,  5,  8, 10, 13, 15, 16, 17]), array([6, 6, 6, 2, 6, 6, 6, 6, 9, 4]))
[0.0093 0.0001 0.0151 0.0346 0.014  0.0343 0.019  0.0336 0.0439 0.034 ]


In [12]:
# save as dataframe

p_vals_e_df = pd.DataFrame(p_vals_e)

p_vals_e_df.to_csv(f"pvals_enriched.tsv", sep="\t", index=False)

In [15]:
p_vals_d_df = pd.DataFrame(p_vals_d)

p_vals_d_df.to_csv(f"pvals_depleted.tsv", sep="\t", index=False)

In [38]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/exports/igmm/eddie/GWAS-annotations/annotation-env/lib']
    define_macros = [